import React from "react"; //MIT LICENSE < https://github.com/facebook/react/ >
import { Container, Col, Row, ListGroup, Image } from "react-bootstrap"; //MIT LICENSE < https://github.com/react-bootstrap/react-bootstrap >
import fileFormat from "../../assets/csvFileFormat.PNG"; //LOCAL IMAGE FILE

const About = () => {
  return (
    <Container>
      <Row>
        <Col>
          <br></br>
          <h2 className="text-left">About</h2>
          <br></br>
        </Col>
      </Row>
      <Col>
        <h4 className="text-left">Functionality</h4>
        <p className="text-left">
          <ul>
          <li>
            Create manual and automatic cloud-managed driver update policies
          </li>
          <li>
            Add/remove Azure AD devices to your policies
          </li>
          <li>
            Browse driver and firmware updates that are available for your devices
          </li>
          <li>
            Approve and schedule driver updates
          </li>
          <li>
            Suspensions of approvals
          </li>
          <li>
            Unenroll devices from driver management
          </li>
          </ul>
        </p>
      </Col>
      <br></br>
      <Col>
        <h4 className="text-left">Known Issues for Web Application</h4>
        <p className="text-left">
            "Refresh" required after large batch device add/remove to accurately
            portray device count
        </p>
      </Col>
      <br></br>
      <Col>
        <h4 className="text-left">Batch Device Add/Remove CSV File Format</h4>
        <p className="text-left">
          Easily create a list of devices in Excel using the following format
        </p>
        <p className="text-left">
       <ul>
          <li>
            All fields need to be included (@odata.type, id, #microsoft.graph.windowsUpdates.azureADDevice)
          </li>
          <li>
            Add Azure AD device Ids - all values are case sensitive
          </li>
          <li>
            Save file as CSV - only CSV files can be uploaded for batch changes
          </li>
          <li>
            Limit each CSV to less than 200 devices - create multiple files if needed
          </li>
          </ul>
          </p>
        <Image className="mb-5" src={fileFormat} fluid />
      </Col>
      <br></br>
      <Col>
        <h4 className="text-left">Support</h4>
        <p className="text-left">
          For issues, please send email to wufbdrivers@microsoft.com with
          the following information:
        </p>
        <p className="text-left">
          <ol>
          <li>
            Description of the issue
          </li>
          <li>
            AAD Device ID (this can be found by issuing this
          command locally through PowerShell: dsregcmd /status)
          </li>
          <li>
            After checking for updates in Windows Update,
          please attach the log generated by the&nbsp; 
          <a href="http://aka.ms/WUCopyLogs">Windows Update Log Collection Tool
          </a>
          . These logs contain information that will allow us to search for
          related service events and device settings.
          </li>
          <li>
            Policy ID created in the web application
          </li>
          <li>
            Screenshots relevant to the issue
          </li>
          </ol>
        </p>
      </Col>
    </Container>
  );
};

export { About };
